# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f94099326f33719b0325eb0b62c2c6a3d2cdeb16e8c27112cfc3ab2232d2df625ae34d906408ac90912e9177918eadf68c912c367d0ea96780e7d460e2829b

test:
  secret_key_base: 72709f77eb0d0e2ff1f5c8a1d3698282136ebeb6f44a1855c92bdf2fdbaa468f5a7f1d2105f530185c1f6995a8e30b8b276fc8f717e182dd457e641642b05486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
